---

- block:
      
    - name: "Install Docker Repo Container"
      include_tasks: installdockerrepo.yml
      tags: [repoinstall]
      when : 
        - docker_repo_install == "yes"

    - name: "Retag and push images."
      include_tasks: retagimages.yml

  become: true




